# --- conftest.py ---
import pytest
import os
import shutil
import time
import jax
import wandb
import gc
from _pytest._code.code import ExceptionInfo

@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Hook to prevent memory leaks by removing exception info after test completion."""
    outcome = yield
    rep = outcome.get_result()
    setattr(item, "rep_" + rep.when, rep)

    # Remove exception info, since it causes excessive memory usage and workers crash
    if call.excinfo and isinstance(call.excinfo, ExceptionInfo):
        call.excinfo = None

@pytest.fixture(autouse=True)
def cleanup_global_state():
    """Clean up global state before and after each test to prevent state pollution."""
    # Before test: Clean up any existing WandB runs
    if wandb.run is not None:
        try:
            wandb.finish()
        except:
            pass  # Ignore errors during cleanup
    
    yield  # Run the test
    
    # After test: Clean up WandB state and force garbage collection
    if wandb.run is not None:
        try:
            wandb.finish()
        except:
            pass  # Ignore errors during cleanup
    
    # Force garbage collection to free memory
    gc.collect()

@pytest.fixture(autouse=True, scope="module")
def cleanup_jax_state():
    """Clean JAX compilation cache between test modules to prevent memory accumulation."""
    yield  # Run all tests in the module
    
    # After module: Clear JAX caches and force garbage collection
    try:
        jax.clear_caches()
    except:
        pass  # Ignore errors if clearing fails
    
    # Force garbage collection after clearing JAX caches
    gc.collect()

@pytest.hookimpl(tryfirst=True)
def pytest_runtest_setup(item):
    """Clear JAX caches before each test to manage memory usage."""
    # Clear JAX caches every 10 tests to prevent excessive memory usage
    if hasattr(item.session, '_test_count'):
        item.session._test_count += 1
    else:
        item.session._test_count = 1
    
    if item.session._test_count % 10 == 0:
        try:
            jax.clear_caches()
            gc.collect()
        except:
            pass

@pytest.hookimpl(tryfirst=True)
def pytest_runtest_teardown(item, nextitem):
    """Clean up after each test to prevent memory leaks."""
    # Force garbage collection after each test
    gc.collect()
    
    # Clear JAX caches every 20 tests to manage memory
    if hasattr(item.session, '_test_count') and item.session._test_count % 20 == 0:
        try:
            jax.clear_caches()
            gc.collect()
        except:
            pass

def pytest_sessionfinish(session, exitstatus):
    """
    Clean up temporary directories after all tests in the session have run.
    Using pytest_sessionfinish is generally safer than teardown_module for global cleanup.
    """
    # Final WandB cleanup
    if wandb.run is not None:
        try:
            wandb.finish()
        except:
            pass
    
    # Final JAX cleanup
    try:
        jax.clear_caches()
    except:
        pass
    
    # Final garbage collection
    gc.collect()
    
    tmp_dir = "/tmp"
    # Be cautious with this. A more targeted cleanup based on specific prefixes
    # generated by your tests is highly recommended.
    prefixes_to_clean = ["mz_test_", "test_orbax_", "orbax-checkpoint-manager-"] # Add more specific prefixes

    print(f"\nRunning session cleanup in {tmp_dir} for prefixes: {prefixes_to_clean}")
    cleaned_count = 0
    for item in os.listdir(tmp_dir):
        item_path = os.path.join(tmp_dir, item)
        if os.path.isdir(item_path):
            for prefix in prefixes_to_clean:
                if item.startswith(prefix):
                    try:
                        time.sleep(0.2) # Give some time for file handles to release
                        shutil.rmtree(item_path)
                        print(f"Cleaned up: {item_path}")
                        cleaned_count += 1
                    except Exception as e:
                        print(f"Warning: Could not remove test directory {item_path}: {e}")
                    break # Move to next item in /tmp
    if cleaned_count == 0:
        print("No specific temporary test directories found to clean.") 